# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0e\x41uthentication\";\n\x15\x41uthenticationMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\x16\x41uthenticationResponse\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"\x1e\n\x0fValidateMessage\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"K\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0b\n\x03sub\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\" \n\x11InvalidateMessage\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"(\n\x12InvalidateResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x32\x96\x02\n\x0b\x41uthService\x12_\n\x0c\x61uthenticate\x12%.Authentication.AuthenticationMessage\x1a&.Authentication.AuthenticationResponse\"\x00\x12O\n\x08validate\x12\x1f.Authentication.ValidateMessage\x1a .Authentication.ValidateResponse\"\x00\x12U\n\ninvalidate\x12!.Authentication.InvalidateMessage\x1a\".Authentication.InvalidateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATIONMESSAGE']._serialized_start=30
  _globals['_AUTHENTICATIONMESSAGE']._serialized_end=89
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=91
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=128
  _globals['_VALIDATEMESSAGE']._serialized_start=130
  _globals['_VALIDATEMESSAGE']._serialized_end=160
  _globals['_VALIDATERESPONSE']._serialized_start=162
  _globals['_VALIDATERESPONSE']._serialized_end=237
  _globals['_INVALIDATEMESSAGE']._serialized_start=239
  _globals['_INVALIDATEMESSAGE']._serialized_end=271
  _globals['_INVALIDATERESPONSE']._serialized_start=273
  _globals['_INVALIDATERESPONSE']._serialized_end=313
  _globals['_AUTHSERVICE']._serialized_start=316
  _globals['_AUTHSERVICE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
